# Generated by Django 2.1.5 on 2019-01-16 16:59

import datetime
from django.db import migrations, models
from datetime import timezone  # Corrected import

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                # Corrected the default datetime to use timezone.utc instead of utc
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 1, 16, 16, 59, 36, 459183, tzinfo=timezone.utc))),
            ],
        ),
    ]
